spring:
  datasource:
    password: 123456
    username: root
    url: jdbc:mysql://localhost:3306/payment-center?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: payment-center
server:
  port: 8888
eureka:
  instance:
    hostname: payment-center

  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

